### ISSUE TITLE
Back-end Tracking Issues

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/CTFPro#1]
Please list down all the back-end requirements:
- [x] API support for Vagrant VirtualBox #5 
- [x] API support for Vagrant AWS #5
- [x] Create all instances for VirtualBox and AWS #5
- [x] Delete all instances for VirtualBox and AWS #5
- [ ] Start/Stop/Check specific VM for VirtualBox #7 
- [ ] Start/Stop/Check specific VM for AWS #7
- [ ] Multiple users support
- [ ] Multiple component support

**Comment by ariscahyadi** [comment]
Hi @TunSiang ... I just want to confirm we still didn't have features to /check/start/stop specific VM with name.

**Comment by TunSiang** [comment]
right now, i only have have delete for specific VM with name and get information for specific VM with name. 
But i can add those features, as well as a get all VM from AWS feature. 

vb wise, no.

**Comment by ariscahyadi** [comment]
Sorry... I am a little bit confused :)

Based on my understanding of your code, we only have these:
For VB:
- Create, start, stop delete and check all instances

For AWS:
- Create, start, stop, and check all instances
- Delete specific instance

**Comment by TunSiang** [comment]
I will update the codes, you can check it on Monday. I think it will clear up any issues. 
Sorry for the confusion.

**Comment by TunSiang** [comment]
updated the apiServer.py with a new PR, contains the codes for.
Starting/halting specific AWS instance using name as a reference,
getting specific AWS instance information using name as a reference, and getting all AWS instances information.

**Comment by TunSiang** [comment]
Added the features for VB such as, 
delete, start, stop specific VB instance,
get specific VB instance info as well as all VB instances info

**Comment by ariscahyadi** [comment]
> Added the features for VB such as,
> delete, start, stop specific VB instance,
> get specific VB instance info as well as all VB instances info

Did you add these features with the same PR #7 ?

**Comment by TunSiang** [comment]
Yep @ariscahyadi
