### ISSUE TITLE
Front-end Tracking Issues

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/CTFPro#2]
Please list down all front-end requirements:
- [x] Web-based UI Dashboard #4 
- [x] Login Authentication #13 
- [x] Show the components for each user #4 
- [x] Show status of the components #4
- [ ] Submit new component specification
- [ ] Control the status of the component
- [x] Show all components for the administrator #4
