### ISSUE TITLE
Database Tracking Issues

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/CTFPro#3]
Please list down all the database requirements:
- [ ] SQL database
- [ ] Database Schema for Users
- [ ] Database Schema for Components
- [ ] Database (Table) initialization feature
- [ ] Database API Query
